import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:injectable/injectable.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'notes/notes_dao.dart';
import 'notes/notes_table.dart';

// Generated by drift_dev when running `build_runner build`
part 'app_database.g.dart';

@LazySingleton()
@DriftDatabase(tables: [NotesTable], daos: [NotesDao])
class AppDatabase extends _$AppDatabase {
  // you should bump this number whenever you change or add a table definition.
  // Migrations are covered later in the documentation.

  AppDatabase() : super(_openConnection()) {
    driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  }

  AppDatabase.forTesting(DatabaseConnection connection) : super(connection);

  @override
  int get schemaVersion => 1;

  // Future<void> insertNotes
}

LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}
