import 'package:drift/drift.dart';
import 'package:injectable/injectable.dart';
import 'connection/connection.dart' as impl;

import 'notes/notes_dao.dart';
import 'notes/notes_table.dart';

// Generated by drift_dev when running `build_runner build`
part 'app_database.g.dart';

@LazySingleton()
@DriftDatabase(tables: [NotesTable], daos: [NotesDao])
class AppDatabase extends _$AppDatabase {
  // you should bump this number whenever you change or add a table definition.
  // Migrations are covered later in the documentation.

  AppDatabase() : super(impl.connect()) {
    driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  }

  AppDatabase.forTesting(DatabaseConnection connection) : super(connection);

  @override
  int get schemaVersion => 1;

  // Future<void> insertNotes
}
